# Supabase local config — ports 5442x

[api]
enabled = true
port = 54421
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54422
major_version = 15

[studio]
enabled = true
port = 54423
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54424
smtp_port = 5445
pop3_port = 54410

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
port = 54425
