# Supabase local config — ports 1432x

[api]
enabled = true
port = 14321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 14322
major_version = 15

[studio]
enabled = true
port = 14323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 14324
smtp_port = 1425
pop3_port = 14110

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
port = 14325
