# Supabase local config — ports 9432x

[api]
enabled = true
port = 94321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 94322
major_version = 15

[studio]
enabled = true
port = 94323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 94324
smtp_port = 9425
pop3_port = 94110

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[analytics]
enabled = false
port = 94325
