-- AlterTable
ALTER TABLE "User" ADD COLUMN     "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "full_name" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "is_active" BOOLEAN NOT NULL DEFAULT true;
