"use client";

import { useState, useTransition } from "react";
import { cn } from "@/core/utils/cn";
import { Button } from "@/core/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/core/ui/card";
import {
  Eye,
  FileText,
  Trash2,
  Search,
  ChevronLeft,
  ChevronRight,
  Loader2,
} from "lucide-react";
import { deleteReport } from "../actions";
import { toast } from "sonner";
import type { ReportWithUser } from "../queries";

interface ReportsTableProps {
  reports: ReportWithUser[];
  selectedReportId: number | null;
  onSelectReport: (report: ReportWithUser) => void;
  onExportReport: (report: ReportWithUser) => void;
}

function formatDateTime(date: Date) {
  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  }).format(new Date(date));
}

function formatDateRange(from: Date, to: Date) {
  const fmt = new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
  });
  return `${fmt.format(new Date(from))} – ${fmt.format(new Date(to))}`;
}

export function ReportsTable({
  reports,
  selectedReportId,
  onSelectReport,
  onExportReport,
}: ReportsTableProps) {
  const [deletingId, setDeletingId] = useState<number | null>(null);
  const [isPending, startTransition] = useTransition();

  function handleDelete(reportId: number) {
    if (!confirm("Delete this report? This action cannot be undone.")) return;

    startTransition(async () => {
      setDeletingId(reportId);
      const result = await deleteReport(reportId);
      if (result.success) {
        toast.success("Report deleted.");
      } else {
        toast.error("Failed to delete report.");
      }
      setDeletingId(null);
    });
  }

  return (
    <Card>
      <CardHeader className="border-b border-border bg-card">
        <div className="flex items-center justify-between">
          <CardTitle className="text-xs leading-4 font-semibold tracking-wider text-foreground uppercase">
            Generated Report Data
          </CardTitle>
          <Button variant="outline" size="xs" disabled>
            <Search className="h-3 w-3" />
            Filter
          </Button>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        <div className="hidden overflow-x-auto md:block">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-border bg-card text-xs font-medium tracking-wider text-muted-foreground uppercase">
              <tr>
                <th className="px-4 py-3">Report ID</th>
                <th className="px-4 py-3">Date Generated</th>
                <th className="px-4 py-3">Type</th>
                <th className="px-4 py-3">Date Range</th>
                <th className="px-4 py-3">Generated By</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/50">
              {reports.map((row, i) => (
                <tr
                  key={row.report_id}
                  onClick={() => onSelectReport(row)}
                  className={cn(
                    "h-10 cursor-pointer transition-colors hover:bg-muted",
                    selectedReportId === row.report_id && "bg-primary/10",
                    selectedReportId !== row.report_id && i % 2 === 1 && "bg-muted/40"
                  )}
                >
                  <td className="px-4 py-2 font-medium text-primary underline-offset-4 hover:underline cursor-pointer">
                    {row.report_code}
                  </td>
                  <td className="px-4 py-2">
                    {formatDateTime(row.generated_at)}
                  </td>
                  <td className="px-4 py-2">{row.type}</td>
                  <td className="px-4 py-2 text-muted-foreground">
                    {formatDateRange(row.date_from, row.date_to)}
                  </td>
                  <td className="px-4 py-2">{row.user.email}</td>
                  <td className="px-4 py-2">
                    <div className="flex justify-end gap-1">
                      <Button
                        variant="ghost"
                        size="icon-xs"
                        className="text-muted-foreground hover:text-primary"
                        title="View"
                        onClick={(event) => {
                          event.stopPropagation();
                          onSelectReport(row);
                        }}
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon-xs"
                        className="text-muted-foreground hover:text-primary"
                        title="Download"
                        onClick={(event) => {
                          event.stopPropagation();
                          onExportReport(row);
                        }}
                      >
                        <FileText className="h-4 w-4" />
                      </Button>
                      <Button
                        variant="ghost"
                        size="icon-xs"
                        className="text-muted-foreground hover:text-destructive"
                        title="Delete"
                        disabled={isPending && deletingId === row.report_id}
                        onClick={(event) => {
                          event.stopPropagation();
                          handleDelete(row.report_id);
                        }}
                      >
                        {isPending && deletingId === row.report_id ? (
                          <Loader2 className="h-4 w-4 animate-spin" />
                        ) : (
                          <Trash2 className="h-4 w-4" />
                        )}
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
              {reports.length === 0 && (
                <tr>
                  <td
                    colSpan={6}
                    className="py-16 text-center text-muted-foreground text-sm"
                  >
                    No reports generated yet. Use the filter bar above to
                    generate your first report.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        <div className="flex flex-col gap-3 p-4 md:hidden">
          {reports.map((row) => (
            <div
              key={row.report_id}
              onClick={() => onSelectReport(row)}
              className={cn(
                "cursor-pointer rounded border border-border bg-card p-3",
                selectedReportId === row.report_id && "border-primary bg-primary/10"
              )}
            >
              <div className="mb-2 flex items-center justify-between">
                <span className="font-medium text-primary">
                  {row.report_code}
                </span>
                <span className="text-xs text-muted-foreground">
                  {formatDateTime(row.generated_at)}
                </span>
              </div>
              <div className="mb-1 text-sm">{row.type}</div>
              <div className="mb-2 text-xs text-muted-foreground">
                {formatDateRange(row.date_from, row.date_to)} ·{" "}
                {row.user.email}
              </div>
              <div className="flex gap-1">
                <Button
                  variant="ghost"
                  size="icon-xs"
                  onClick={(event) => {
                    event.stopPropagation();
                    onSelectReport(row);
                  }}
                >
                  <Eye className="h-4 w-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon-xs"
                  onClick={(event) => {
                    event.stopPropagation();
                    onExportReport(row);
                  }}
                >
                  <FileText className="h-4 w-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="icon-xs"
                  className="hover:text-destructive"
                  disabled={isPending && deletingId === row.report_id}
                  onClick={(event) => {
                    event.stopPropagation();
                    handleDelete(row.report_id);
                  }}
                >
                  <Trash2 className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ))}
          {reports.length === 0 && (
            <p className="py-12 text-center text-muted-foreground text-sm">
              No reports generated yet.
            </p>
          )}
        </div>

        <div className="flex items-center justify-between border-t border-border bg-card p-3 text-xs text-muted-foreground">
          <span>
            Showing {reports.length} of {reports.length} reports
          </span>
          <div className="flex gap-1">
            <Button
              variant="outline"
              size="icon-xs"
              disabled
              className="opacity-50"
            >
              <ChevronLeft className="h-3 w-3" />
            </Button>
            <Button variant="outline" size="icon-xs" disabled className="opacity-50">
              <ChevronRight className="h-3 w-3" />
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
