"use client";

import { cn } from "@/core/utils/cn";
import { Button } from "@/core/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/core/ui/card";
import {
  Eye,
  FileSpreadsheet,
  FileText,
  Filter,
  ChevronLeft,
  ChevronRight,
} from "lucide-react";

interface ReportRow {
  id: string;
  dateGenerated: string;
  type: string;
  dateRange: string;
  generatedBy: string;
}

const reportData: ReportRow[] = [
  {
    id: "RPT-2023-104",
    dateGenerated: "Oct 24, 2023 14:30",
    type: "Inventory Levels",
    dateRange: "Sep 01 - Oct 31",
    generatedBy: "System Auto",
  },
  {
    id: "RPT-2023-103",
    dateGenerated: "Oct 23, 2023 09:15",
    type: "Donor Acquisition",
    dateRange: "Q3 2023",
    generatedBy: "Dr. Sarah Jenkins",
  },
  {
    id: "RPT-2023-102",
    dateGenerated: "Oct 20, 2023 16:45",
    type: "Lab Testing Yields",
    dateRange: "Oct 01 - Oct 20",
    generatedBy: "Mark Tech",
  },
  {
    id: "RPT-2023-101",
    dateGenerated: "Oct 15, 2023 08:00",
    type: "Dispensation Logs (NICU)",
    dateRange: "Sep 01 - Sep 30",
    generatedBy: "System Auto",
  },
];

function ReportActions() {
  return (
    <div className="flex justify-end gap-1">
      <Button
        variant="ghost"
        size="icon-xs"
        className="text-muted-foreground hover:text-primary"
        title="View"
      >
        <Eye className="h-4 w-4" />
      </Button>
      <Button
        variant="ghost"
        size="icon-xs"
        className="text-muted-foreground hover:text-primary"
        title="Export CSV"
      >
        <FileSpreadsheet className="h-4 w-4" />
      </Button>
      <Button
        variant="ghost"
        size="icon-xs"
        className="text-muted-foreground hover:text-primary"
        title="Export PDF"
      >
        <FileText className="h-4 w-4" />
      </Button>
    </div>
  );
}

export function ReportsTable() {
  return (
    <Card>
      <CardHeader className="border-b border-border bg-card">
        <div className="flex items-center justify-between">
          <CardTitle className="text-xs leading-4 font-semibold tracking-wider text-foreground uppercase">
            Generated Report Data
          </CardTitle>
          <Button variant="outline" size="xs">
            <Filter className="h-3 w-3" />
            Filter
          </Button>
        </div>
      </CardHeader>
      <CardContent className="p-0">
        {/* Desktop Table */}
        <div className="hidden overflow-x-auto md:block">
          <table className="w-full text-left text-sm">
            <thead className="border-b border-border bg-card text-xs font-medium tracking-wider text-muted-foreground uppercase">
              <tr>
                <th className="px-4 py-3">Report ID</th>
                <th className="px-4 py-3">Date Generated</th>
                <th className="px-4 py-3">Type</th>
                <th className="px-4 py-3">Date Range</th>
                <th className="px-4 py-3">Generated By</th>
                <th className="px-4 py-3 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/50">
              {reportData.map((row, i) => (
                <tr
                  key={row.id}
                  className={cn(
                    "h-10 transition-colors hover:bg-muted",
                    i % 2 === 1 && "bg-card"
                  )}
                >
                  <td className="px-4 py-2 font-medium text-primary">
                    {row.id}
                  </td>
                  <td className="px-4 py-2">{row.dateGenerated}</td>
                  <td className="px-4 py-2">{row.type}</td>
                  <td className="px-4 py-2 text-muted-foreground">
                    {row.dateRange}
                  </td>
                  <td className="px-4 py-2">{row.generatedBy}</td>
                  <td className="px-4 py-2">
                    <ReportActions />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Mobile Cards */}
        <div className="flex flex-col gap-3 p-4 md:hidden">
          {reportData.map((row) => (
            <div
              key={row.id}
              className="rounded border border-border bg-card p-3"
            >
              <div className="mb-2 flex items-center justify-between">
                <span className="font-medium text-primary">{row.id}</span>
                <span className="text-xs text-muted-foreground">
                  {row.dateGenerated}
                </span>
              </div>
              <div className="mb-1 text-sm">{row.type}</div>
              <div className="mb-2 text-xs text-muted-foreground">
                {row.dateRange} · {row.generatedBy}
              </div>
              <ReportActions />
            </div>
          ))}
        </div>

        {/* Pagination */}
        <div className="flex items-center justify-between border-t border-border bg-card p-3 text-xs text-muted-foreground">
          <span>Showing 1-4 of 24 reports</span>
          <div className="flex gap-1">
            <Button
              variant="outline"
              size="icon-xs"
              disabled
              className="opacity-50"
            >
              <ChevronLeft className="h-3 w-3" />
            </Button>
            <Button variant="outline" size="icon-xs">
              <ChevronRight className="h-3 w-3" />
            </Button>
          </div>
        </div>
      </CardContent>
    </Card>
  );
}
