import type { GeneratedReport } from "./queries";

const PROGRAM_LABELS: Record<string, string> = {
  SUPSUP_TODO: "Supsup Todo",
  MILKY_WAY: "Milky Way",
  MOMS_ACT: "Mom's Act",
};

function volume(value: number) {
  return `${Math.round(value).toLocaleString()} mL`;
}

function csvCell(value: unknown) {
  const text = value === null || value === undefined ? "" : String(value);
  return `"${text.replaceAll('"', '""')}"`;
}

function pushRow(rows: unknown[][], ...cells: unknown[]) {
  rows.push(cells);
}

function appendTable(
  rows: unknown[][],
  title: string,
  columns: string[],
  data: (string | number)[][]
) {
  pushRow(rows, title);
  pushRow(rows, ...columns);
  if (data.length === 0) {
    pushRow(rows, "No records found.");
  } else {
    data.forEach((row) => pushRow(rows, ...row));
  }
  pushRow(rows);
}

export function isGeneratedReport(value: unknown): value is GeneratedReport {
  return (
    typeof value === "object" &&
    value !== null &&
    "title" in value &&
    "period" in value &&
    "category" in value &&
    "dateFrom" in value &&
    "dateTo" in value &&
    "generatedAt" in value
  );
}

export function reportToCsvRows(report: GeneratedReport) {
  const rows: unknown[][] = [];

  pushRow(rows, "Report ID", report.reportCode ?? "");
  pushRow(rows, "Report Title", report.title);
  pushRow(rows, "Period", report.period);
  pushRow(rows, "Category", report.category);
  pushRow(rows, "Date Range", `${report.dateFrom} - ${report.dateTo}`);
  pushRow(rows, "Generated By", report.generatedBy ?? "");
  pushRow(rows, "Generated At", report.generatedAt);
  pushRow(rows);

  pushRow(rows, "Summary");
  const summaryRows: [string, string][] = [];
  if (report.collection) summaryRows.push(["Total Collected", volume(report.collection.totalCollectedVolume)]);
  if (report.processing) summaryRows.push(["Total Processed", volume(report.processing.pasteurizationBatches.totalProcessedVolume)]);
  if (report.inventory) summaryRows.push(["Available Stock", volume(report.inventory.availableStockVolume)]);
  if (report.dispensing) summaryRows.push(["Total Dispensed", volume(report.dispensing.totalDispensedVolume)]);
  if (report.disposal) summaryRows.push(["Total Disposed", volume(report.disposal.totalDisposedVolume)]);
  if (report.donor) summaryRows.push(["Registered Donors", report.donor.registeredDonors.toLocaleString()]);
  if (report.recipient) summaryRows.push(["Registered Recipients", report.recipient.registeredRecipients.toLocaleString()]);
  summaryRows.forEach(([label, value]) => pushRow(rows, label, value));
  if (summaryRows.length === 0) pushRow(rows, "No summary data.");
  pushRow(rows);

  if (report.collection) {
    appendTable(
      rows,
      "Collection by Program",
      ["Program", "Records", "Volume"],
      report.collection.collectionsByProgram.map((row) => [
        PROGRAM_LABELS[row.program] ?? row.program,
        row.count,
        volume(row.volume),
      ])
    );
    appendTable(
      rows,
      "Collection by Donor",
      ["Donor", "Records", "Volume"],
      report.collection.collectionsByDonor.map((row) => [
        row.donorName,
        row.count,
        volume(row.volume),
      ])
    );
  }

  if (report.processing) {
    appendTable(rows, "Processing Tests", ["Stage", "Total Tested", "Passed", "Failed", "Awaiting Result"], [
      [
        "Pre-pasteurization",
        report.processing.prePasteurization.totalTested,
        report.processing.prePasteurization.passed,
        report.processing.prePasteurization.failed,
        report.processing.prePasteurization.awaitingResult,
      ],
      [
        "Post-pasteurization",
        report.processing.postPasteurization.totalTested,
        report.processing.postPasteurization.passed,
        report.processing.postPasteurization.failed,
        report.processing.postPasteurization.awaitingResult,
      ],
    ]);
  }

  if (report.dispensing) {
    appendTable(
      rows,
      "Dispensing by Source",
      ["CTN / Batch", "Volume"],
      report.dispensing.volumeBySource.map((row) => [row.source, volume(row.volume)])
    );
    appendTable(
      rows,
      "Dispensing by Payment Status",
      ["Payment Status", "Transactions", "Volume"],
      report.dispensing.paymentStatusSummary.map((row) => [
        row.status.replaceAll("_", " "),
        row.count,
        volume(row.volume),
      ])
    );
    appendTable(
      rows,
      "Dispensing by Staff",
      ["Released By", "Transactions", "Volume"],
      report.dispensing.releasedByStaff.map((row) => [
        row.staffName,
        row.count,
        volume(row.volume),
      ])
    );
  }

  if (report.inventory) {
    appendTable(rows, "Inventory", ["Available Stock", "Inventory Records", "Available Batches", "Expired Collections", "Disposed Batches"], [
      [
        volume(report.inventory.availableStockVolume),
        report.inventory.inventoryRecords,
        report.inventory.availableBatches,
        report.inventory.expiredCollectionCount,
        report.inventory.disposedBatches,
      ],
    ]);
  }

  if (report.disposal) {
    appendTable(
      rows,
      "Disposal Reasons",
      ["Reason", "Records", "Volume"],
      report.disposal.reasons.map((row) => [row.reason, row.count, volume(row.volume)])
    );
  }

  if (report.donor) {
    appendTable(
      rows,
      "Donor Collections",
      ["Donor", "Collections", "Volume"],
      report.donor.donorCollections.map((row) => [
        row.donorName,
        row.count,
        volume(row.volume),
      ])
    );
  }

  if (report.recipient) {
    appendTable(rows, "Recipient Service", ["Recipients Served", "Beneficiaries Served", "Requests"], [
      [
        report.recipient.recipientsServed,
        report.recipient.beneficiariesServed,
        report.recipient.requestCount,
      ],
    ]);
  }

  return rows;
}

export function rowsToCsv(rows: unknown[][]) {
  return rows.map((row) => row.map(csvCell).join(",")).join("\r\n");
}

export function downloadCsv(filename: string, csv: string) {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(url);
}

export function safeFilename(value: string) {
  return value.replace(/[^a-z0-9-_]+/gi, "-").replace(/^-+|-+$/g, "");
}
